### ISSUE TITLE
Instanciar as métodos ou usar o STATIC?

### ISSUE THREAD

**Issue by ViniciusDantz** [ViniciusDantz/Calculadora_Avancada-ims#3]
Instanciar funções no main pode não ser a única forma de criar usar a função das classes.
A palavra reservada Static usada em métodos de classes quer dizer que a classe não precisa ser instanciada para chamar este método. Podemos usar, por exemplo: "Log.log(x, y);" Onde: "Log" refere-se à própria classe e não a um objeto, e ".log" refere-se ao método que está dentro da classe "Log".
Então, usar static em tudo e apagar as instâncias no main ou instanciar tudo sem o static?

**Comment by ronaldojrk** [comment]
acho valido usar static em tudo

**Comment by ViniciusDantz** [comment]
@LaraFer10, @theusmoraes e @ronaldojrk coloquem o _STATIC_ nas suas operações passadas(soma, multiplicação e subtração), retirem a instancia dessas operações do main e arrumem o próprio método la no seu respectivo switch-case.

**Comment by ronaldojrk** [comment]
to fazendo
